### ISSUE TITLE
Can still interactive with ART3MI5

### ISSUE THREAD

**Issue by Zquiz** [lukelee365/GreenHornTerminalGit#17]
Still able to get "what is IPCC?" button if I didn't open the mail before breach happens and she goes offline.

**Comment by lukelee365** [comment]
ShouldBeFixed

**Comment by Zquiz** [comment]
Still there

**Comment by Zquiz** [comment]
Also there is a bug if you open the mail first before the yes and no comes the IPCC is gone for good
