### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by vidhiss** [lukelee365/GreenHornTerminalGit#4]
1. Volume to be reduced (notification for email) 
2. Sound required for every time ART3MI5 sends a message
3. Lag in tap sound. Possibly the sound needs to be edited. 
4. New security sound. Also please reduce the volume.

**Comment by Zquiz** [comment]
Not sure it would be a good idea with a sound effect for every time ART3MI5 sends a message. It would make the sound effect play many times after each other. 

Volume for notification for emails has been reduced
Lag in tap sound has been fixed
New security sound

**Comment by Zquiz** [comment]
Blop sound for when ART3MI5 is sending the player a message.

**Comment by lukelee365** [comment]
Fixed
